# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-06 13:39
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import markupfield.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('text', markupfield.fields.MarkupField(rendered_field=True)),
                ('text_markup_type', models.CharField(blank=True, choices=[(b'', b'--'), (b'html', 'HTML'), (b'plain', 'Plain'), (b'markdown', 'Markdown'), (b'restructuredtext', 'Restructured Text')], default=None, max_length=30, null=True)),
                ('summary', models.TextField()),
                ('_text_rendered', models.TextField(editable=False)),
                ('created_on', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, 999999), editable=False)),
                ('is_published', models.BooleanField(default=True)),
                ('publish_date', models.DateTimeField(null=True)),
                ('comments_allowed', models.BooleanField(default=True)),
                ('is_rte', models.BooleanField(default=False)),
                ('meta_keywords', models.TextField(blank=True, null=True)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
        migrations.CreateModel(
            name='BlogRoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('text', models.CharField(max_length=100)),
                ('is_published', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user_name', models.CharField(max_length=100)),
                ('user_url', models.URLField()),
                ('email_id', models.EmailField(max_length=254)),
                ('is_spam', models.BooleanField(default=False)),
                ('is_public', models.NullBooleanField()),
                ('user_ip', models.GenericIPAddressField(null=True)),
                ('user_agent', models.CharField(default='', max_length=200)),
                ('comment_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Blog')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reply_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
