# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20160307_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogMeta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tag_line', models.CharField(max_length=100)),
                ('entries_per_page', models.IntegerField(default=10)),
                ('recents', models.IntegerField(default=5)),
                ('recent_comments', models.IntegerField(default=5)),
            ],
        ),
        migrations.AlterModelManagers(
            name='blog',
            managers=[
                ('default', django.db.models.manager.Manager()),
            ],
        ),
    ]
