# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-11 00:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160309_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmeta',
            old_name='entries_per_page',
            new_name='blogs_per_page',
        ),
    ]
